02 delete api endpoints
LukarioMC/COMP-4800-37 pull request #24
Opened 2024-05-15 23:10 UTC by ldiu

DELETE tag, DELETE attachment, and DELETE fact endpoints as well approval PUT. PUT is currently one way as it is not confirmed if an approved fact should be able to be unapproved.

2024-05-16 23:01 UTC, LukarioMC requested changes
Looking good so far, some changes please 👍

2024-05-16 23:01 UTC, LukarioMC commented on app/handlers/factoid.js
> +function deleteFactByID(factoidID) {
Please add function documentation :)

2024-05-16 23:01 UTC, LukarioMC commented on app/handlers/factoid.js
> +function approveFactByID(factoidID) {
Please add function documentation :)

2024-05-16 23:01 UTC, LukarioMC commented on app/routes/api.js
> +        const result = deleteTagforFactoid(parseInt(factoidID), parseInt(categoryID));
I feel like we should do this instead
```suggestion
        const factoidID = parseInt(req.params.factoidID);
        const categoryID = parseInt(req.params.categoryID);

		if (isNaN(factoidID) || isNaN(categoryID)) {
			return res.status(404).send({ message: 'Invalid fact or category in request.' });
		}

        const result = deleteTagforFactoid(factoidID, categoryID);
```

2024-05-16 23:01 UTC, LukarioMC commented on app/routes/api.js
> +
Pretty much same as above :)
```suggestion
        const factoidID = parseInt(req.params.factoidID);
        
		if (isNaN(factoidID)) {
			return res.status(404).send({ message: 'Invalid factoid ID in request.' });
		}
```

2024-05-16 23:01 UTC, LukarioMC commented on app/routes/api.js
> +
Pretty much same as above :)
```suggestion
        const factoidID = parseInt(req.params.factoidID);
        
		if (isNaN(factoidID)) {
			return res.status(404).send({ message: 'Invalid factoid ID in request.' });
		}
```

2024-05-16 23:01 UTC, LukarioMC commented on app/routes/api.js
> +
Pretty much same as above :)
```suggestion
        const attachmentID = parseInt(req.params.attachmentID);

		if (isNaN(attachmentID)) {
			return res.status(404).send({ message: 'Invalid attachment ID in request.' });
		}
```

2024-05-16 23:01 UTC, LukarioMC commented on app/handlers/factoid.js
> +        let result = approveFactStmt.run(id)
Let the handlers above do type-checking and parsing, so you can just simply do:
```suggestion
        let approveFactStmt = db.prepare('UPDATE factoid SET is_approved = 1 WHERE id = ?')
        let result = approveFactStmt.run(factoidID)
```

2024-05-16 23:10 UTC, ldiu commented on app/handlers/factoid.js
> +function deleteFactByID(factoidID) {
:+1:

2024-05-16 23:10 UTC, ldiu commented on app/handlers/factoid.js
> +function approveFactByID(factoidID) {
:persevere:

2024-05-17 00:18 UTC, LukarioMC approved these changes
Looking good so far, approved and merging. 🥳

2024-05-17 00:18 UTC, merged